export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_DEFAULT = 'AUTH_DEFAULT';
export const AUTH_FETCH_USER = 'AUTH_FETCH_USER';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CHECK_COMPANY_IDENTIFY = 'AUTH_CHECK_COMPANY_IDENTIFY';
export const AUTH_LOGIN_OTHER_COMPANY = 'AUTH_LOGIN_OTHER_COMPANY';
export const AUTH_SIGN_UP_EMAIL = 'AUTH_SIGN_UP_EMAIL';
